import { DesktopIconRecord } from './storage/db';

const now = Date.now();

export const DEFAULT_ICONS: Omit<DesktopIconRecord, 'id'>[] = [
    {
        label: 'This PC',
        icon: 'computer',
        colorClass: 'text-blue-300',
        appId: 'explorer',
        position: { x: 20, y: 24 },
        order: 0,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Documents',
        icon: 'folder_open',
        colorClass: 'text-yellow-300',
        appId: 'explorer',
        position: { x: 20, y: 140 },
        order: 1,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Browser',
        icon: 'public',
        colorClass: 'text-green-300',
        appId: 'browser',
        position: { x: 20, y: 256 },
        order: 2,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Terminal',
        icon: 'terminal',
        colorClass: 'text-green-400',
        appId: 'terminal',
        position: { x: 20, y: 372 },
        order: 3,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Timer',
        icon: 'timer',
        colorClass: 'text-red-300',
        appId: 'timer',
        position: { x: 140, y: 24 },
        order: 4,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'JSON Viewer',
        icon: 'data_object',
        colorClass: 'text-amber-300',
        appId: 'jsonviewer',
        position: { x: 140, y: 140 },
        order: 5,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Todo List',
        icon: 'checklist',
        colorClass: 'text-lime-300',
        appId: 'todolist',
        position: { x: 140, y: 256 },
        order: 6,
        createdAt: now,
        updatedAt: now,
    },
    {
        label: 'Recycle Bin',
        icon: 'delete',
        colorClass: 'text-gray-300',
        appId: 'recyclebin',
        position: { x: 140, y: 372 },
        order: 7,
        createdAt: now,
        updatedAt: now,
    },
];
